---
# tasks file for nginx11

- name: Install NGINX
  hosts: dkochetov-2.devops.rebrain.srwx.net
  become: yes
  tasks:
  - name: Install Nginx
    apt: name=nginx
  notify: Reload nginx
- name: Generate nginx.conf & copy (dkochetov-1; hostname1)
  template:
  src={{ item.src }}
  dest={{ item.dest }}
  mode=0644
  loop:
  -  { src: 'nginx2.j2' , dest: 'dkochetov-2.devops.rebrain.srwx.net/etc/nginx/nginx.conf'}
  -  { src: 'index2.j2' , dest: 'dkochetov-1.devops.rebrain.srwx.net/etc/nginx/nginx.conf'}
  #-  { src: 'hostname2', dest: 'dkochetov-2.devops.rebrain.srwx.net/etc/hostname'}
  notify: Reload nginx
