---
# tasks file for nginx1-2

- name: Install Nginx
  apt: name=nginx
  notify: Autostart webserver

- name: Create site folder
  file:
    path=/home/{{ domain_name }}
    state=directory
    mode=0644

- name: Generate nginx.conf dkocheto-2
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0644
  loop:
    -  { src: 'nginx2.j2' , dest: '{{ nginx_config_remote }}/nginx.conf'}
    -  { src: 'index.html' , dest: '{{ site_folder_remote }}/{{ domain_name }}/index.html'}
    -  { src: 'hostname2' ,  dest: '/etc/hostname'}
  notify: Reload nginx
