---
- hosts: all
  tasks:
    - name: Install package nginx
      apt: name=nginx update_cache=yes
      notify: Starting service nginx
    - name: Install nginx config files
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        notify: Reload nginx

  handlers:
    - name: Reload nginx
      service: name=nginx state=reloaded
      sudo: yes
    - name: Starting service nginx
      service: name=nginx state=started
      sudo: yes