---
- hosts: all
  tasks:
      - name: Install package nginx
        apt: name=nginx update_cache=yes
        notify: Restart Nginx
  handlers:
      - name: Restart Nginx
        ansible.builtin.service:
          name: nginx 
          state: restarted
        
