do_token        = "......."
my_ssh_devops   = "ssh-rsa ....."
rebrain         = "ssh-rsa ....."
ssh_fingerprint = "....."
#aws_access_key  = "........."
#aws_secret_key  = "......."
my_ssh_devops1 = "/home/inblade/.ssh/id_rsa"
