do_token        = "......"
my_ssh_devops   = "ssh-rsa ....."
another         = "ssh-rsa ....."
ssh_fingerprint = "123456"
#aws_access_key  = "....."
#aws_secret_key  = "....."
my_ssh_devops1 = "/home/inblade/.ssh/id_rsa"
