---
# tasks file for nginx-settings

- name: Install package nginx
  apt:
    name=nginx
    update_cache=yes
  notify: Starting service nginx

- name: Create site folder
  file:
    path=/home/{{ domain_name }}
    state=directory

- name: Autostart webserver
  service:
    name=nginx
    state=started
    enabled=yes

- name: Generate HTTP nginx.conf
  template:
    src=nginx.j2
    dest={{ nginx_config_remote }}/nginx.conf mode=0644
  notify: Reload nginx

- name: Generate title page
  template:
    src=index.j2
    dest={{ site_folder_remote }}/{{ domain_name }}/index.html mode=0644
